// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Toggle between local and remote via environment variable
const USE_LOCAL = process.env.NEXT_PUBLIC_USE_LOCAL_SUPABASE === "true";

// Local Supabase (when running `supabase start`)
const LOCAL_SUPABASE_URL = "http://127.0.0.1:54321";
const LOCAL_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Remote Supabase (from environment variables)
const REMOTE_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const REMOTE_SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const SUPABASE_URL = USE_LOCAL ? LOCAL_SUPABASE_URL : REMOTE_SUPABASE_URL;

const SUPABASE_ANON_KEY = USE_LOCAL
  ? LOCAL_SUPABASE_ANON_KEY
  : REMOTE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing Supabase configuration. Check your .env.local file.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  },
);

// Register OAuth provider token storage
// This captures GitHub access tokens when using OAuth
supabase.auth.onAuthStateChange((event, session) => {
  if (session && session.provider_token) {
    window.localStorage.setItem("oauth_provider_token", session.provider_token);
    console.log("GitHub provider token stored");
  }

  if (session && session.provider_refresh_token) {
    window.localStorage.setItem(
      "oauth_provider_refresh_token",
      session.provider_refresh_token,
    );
    console.log("GitHub refresh token stored");
  }

  if (event === "SIGNED_OUT") {
    window.localStorage.removeItem("oauth_provider_token");
    window.localStorage.removeItem("oauth_provider_refresh_token");
    console.log("OAuth tokens cleared");
  }
});
